version: "3.8"
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --requirepass xVUMmx4gJbEMptdK
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  application:
    container_name: application
    build: .
    ports:
      - "8080:8080"
    links:
      - "redis"

